groups/urls.py
from django.urls import path, include
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),

]

posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<username>/', views.UserPosts.as_view(), name="for_user"),
    path('by/<username>/<pk>/', views.PostDetail.as_view(), name="single"),
    path('delete/<pk>/', views.DeletePost.as_view(), name="delete"),


]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls',namespace='groups')),
    path('posts/', include('posts.urls',namespace='posts')),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
# import misaka
from django.contrib.auth import get_user_model
from django.urls import reverse

# Create your models here.
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, blank=True, default='')
    members = models.ManyToManyField(User, through='GroupMember')
    
    def __str__(self):
        return  self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        # self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username 
 
    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from . import models
from django.shortcuts import get_object_or_404

# Create your views here.
class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name','description')
    model = models.Group

class SingleGroup(LoginRequiredMixin, generic.DetailView):
    model = models.Group

class ListGroups(generic.ListView):
    model = models.Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    
    def get(self, *args, **kwargs):
        group = get_object_or_404(models.Group, slug=self.kwargs.get('slug'))

        try:
            models.GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request,"Warning! you're already a member")
        else: 
            messages.success(self.request, 'You are now a member !!')

        return super().get(self.request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user = self.request.user,
                group__slug = self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group !!')
        else: 
            membership.delete()
            messages.success(self.request,'You have left the group !!')
        return super().get(self.request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block body %}

<div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %} {% block pregroup %}

<div class="container">
    <div class="row">
        <div class="col-6 float-left">
            <h1>{{ group.name }}</h1>
            <h3>Members: {{ group.members.count }}</h3>
        </div>


        <div class="col-6 float-left">
            <br /> {% if user in group.members.all %}
            <a class="btn btn-danger float-right mr-3" href="{% url 'groups:leave' slug=group.slug %}"><span class="fa fa-remove"></span> Leave</a> {% else %}
            <a class="btn btn-primary float-right mr-3" href="{% url 'groups:join' slug=group.slug %}"><span class="fa fa-check"></span> Join</a> {% endif %}
        </div>
    </div>
</div>

{% endblock %} {% block group_content %}

<div class="col-md-12">
    <br /> {% if group.posts.count == 0 %}
    <h2>No posts available</h2>
    {% else %}
    <h4>Posts:</h4>
    <br /> {% for post in group.posts.all %} {% include "posts/_post.html" %} {% endfor %} {% endif %}
</div>

{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %} {% load bootstrap4 %} {% block group_content %}
<h1>Create a new group</h1>
<div class="container mt-3">
    <form action="{% url 'groups:create' %}" method="POST">
        {% csrf_token %} {% bootstrap_form form %}
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %} {% block pregroup %}

<div class="col-md-4">
    {% if user.is_authenticated %}
    <h2>
        Welcome back !!
        <a class="text-black" href="{% url 'posts:for_user' username=user.username %}"> @{{user.username}}</a>

    </h2>
    {% endif %}
    <h2>Groups</h2>
    <h4>Welcome to the groups page !!</h4>
    <br /><br /> {% if user.is_authenticated %}
    <a name="" id="" class="btn btn-primary" href="{% url 'groups:create' %}" role="button">
        <i class="fa fa-plus" aria-hidden="true"></i> Create New Group
    </a>
    {% endif %}
</div>
{% endblock %} {% block group_content %}
<div class="col-md-1"></div>

<div class="col-md-7 p-0 ">
    {% for group in object_list %}
    <a class="btn btn-primary mt-2 ml-1 p-3" href="{% url 'groups:single' slug=group.slug %}">
        <h3 class="text-center">{{group.name}}</h3>
        <div class="container">
            {{group.description_html|safe}}
            <div class="row text-center">
                <div class="col-md-5">
                    <span class="badge" style="font-size: 15px">{{group.members.count}}
                        member{{group.members.count|pluralize}}, {{group.posts.count}}
                        post{{group.posts.count|pluralize}}</span>
                </div>
            </div>
        </div>
    </a>
    {% endfor %}
</div>

{% endblock %}