accounts/urls.py
from django.contrib.auth import views as auth_views
from accounts import views
from django.urls import path, include

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),


]

posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<username>/', views.UserPosts.as_view(), name="for_user"),
    path('by/<username>/<pk>/', views.PostDetail.as_view(), name="single"),
    path('delete/<pk>/', views.DeletePost.as_view(), name="delete"),


]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls',namespace='groups')),
    path('posts/', include('posts.urls',namespace='posts')),
]

templates/base.html
<!DOCTYPE html> {% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/webfonts/all.css' %}">
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src=" {% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
        }
        
        canvas {
            position: absolute;
            left: 0;
            top: 0;
            z-index: -1;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark text-white bg-transparent">
        <a class="navbar-brand" href="{% url 'home' %}">SocialApp</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:for_user' username=user.username  %}">Welcome {{ user.username }} ! </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:all ' %}">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup ' %}">Sign Up</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login ' %}">Log In</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>

    <br />
    <div class="container bg-transparent">
        <br /> {% block body %} {% comment %} BODY {% endcomment %} {% endblock %}
        <br /><br /><br />
    </div>
    <canvas id="canvas" style="position: absolute;left: 0; right: 0;z-index: -1;" width="100%" height="100%">

    </canvas>

</body>

<script src="{% static 'simplesocial/js/master.js ' %}" type="text/javascript"></script>

</html>

templates/index.html
{% extends 'base.html' %}
{% block body %}

    <h1>Welcome to Star Social</h1>

{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block body %}

    <h1>You're now logged in !!</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block body %}

    <h1>Thanks for visiting, come back soon !!</h1>
   
{% endblock %}