posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<username>/', views.UserPosts.as_view(), name="for_user"),
    path('by/<username>/<pk>/', views.PostDetail.as_view(), name="single"),
    path('delete/<pk>/', views.DeletePost.as_view(), name="delete"),


]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls',namespace='groups')),
    path('posts/', include('posts.urls',namespace='posts')),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# import misaka
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        self.message

    def save(self, *args, **kwargs):
        # self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.user.username,
                                                'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="col-md-6 float-left">
    <div class="card bg-dark p-2 mt-2 ml-0">
        <h3>{{ post.message_html|safe }}</h3>
        <div class="media p-0">
            <div class="media-body pl-4">
                <h6>
                    <span><a href="{% url 'posts:for_user' username=post.user.username %}" class="h5" >@{{ post.user.username }}</a></span><br />
                    <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
                </h6>
            </div>
            <div class="media-footer p-0 mt-1 pr-3">
                {% if user.is_authenticated and post.user == user %}
                <a class="btn btn-danger" href="{% url 'posts:delete' pk=post.pk %}"><i class="fa fa-trash" aria-hidden="true"></i></a> {% else %} {% endif %}
            </div>
        </div>
    </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        {% block prepost %} {% endblock  %}
        {% block post_content %}{% endblock  %}
        {% block post_post %} {% endblock  %}
    </div>
</div>
{% endblock  %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %} {% block post_content %}
<h3>Are you sure you want to delete this post?</h3>
<div class="container">
    <br />
    <div class="row">
        <div class="col-md-12 float-left">
            <div class="card bg-dark p-2 mt-2 ml-0">
                <h3>{{ post.message_html|safe }}</h3>
                <div class="media p-0">
                    <div class="media-body pl-4">
                        <div>
                            <div class="mt-1"><a href="{% url 'posts:for_user' username=post.user.username %}" class="h3">@{{ post.user.username }}</a></div>
                            <div class="mt-1"><a class="h4">Message: {{ post.message }}</a></div>
                            <div class="mt-1 mb-3"><time class="time"><a class="h5">Created at: {{ post.created_at }}</a></time></div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 float-left mt-3">
            <form method="POST" class="float-right">
                {% csrf_token %}
                <input type="submit" value="Confirm Delete" class="btn btn-danger">
            </form>
        </div>
    </div>

</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %} {% block post_content %}
<div class="col-md-12 float-left">
    <div class="card bg-dark p-2 mt-2 ml-0">
        <h3>{{ post.message_html|safe }}</h3>
        <div class="media p-0">
            <div class="media-body pl-4">
                <h6>
                    <span class="h1 mt-3">Username: <a href="{% url 'posts:for_user' username=post.user.username %}" class="h1 mt-3" >@{{ post.user.username }}</a></span><br />
                    <p class="mt-3 h3 mb-3">Group: {{ post.group.name }}</p>
                    <p class="mt-3 h4 mb-3">Message: {{ post.message }}</p>
                    <time class="time mt-3"><a class="h6 mt-3">Created at: {{ post.created_at }}</a></time>

                </h6>
            </div>
            <div class="media-footer p-0 mt-1 pr-3">
                {% if user.is_authenticated and post.user == user %}
                <a class="btn btn-danger" href="{% url 'posts:delete' pk=post.pk %}"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a> {% else %} {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %} {% load bootstrap4 %} {% block post_content %}
<h1>Create New Post</h1>
<div class="container mt-3">
    <form method="POST" action="{% url 'posts:create' %}" id="postForm">
        {% csrf_token %} {% bootstrap_form form %}
        <input type="submit" value="Post" class="btn btn-primary btn-large">
    </form>
</div>

{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %} {% block pre_post_content %}

<div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card text-left shadow-lg">
        <div class="card-body">
            <h4 class="card-title">Your Groups</h4>
            <p class="card-text">
                <ul class="list-unstyled">
                    {% for member_group in get_user_groups %}
                    <li class="li-with-bullet">
                        <a class="btn btn-primary" href="{% url 'groups:single' slug=member_group.group.slug %}" role="button"></a>
                    </li>
                    {% endfor %}
                </ul>
            </p>
        </div>
    </div>
    {% endif %}
    <div class="card text-left shadow-lg">
        <div class="card-body">
            <h4 class="card-title">All Groups</h4>
            <p class="card-text">
                <ul class="list-unstyled">
                    {% for other_group in get_other_groups %}
                    <li>
                        <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
                    </li>
                    {% endfor %}
                </ul>
            </p>
        </div>
    </div>
</div>

{% endblock %} {% block post_content %}
<div class="col-md-12">
    {% for post in post_list %} {% include "posts/_post.html" %} {% empty %}
    <h2 class="text-center">No post available !!</h2>
    {% endfor %}
</div>

{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %} {% block prepost %}
<div class="col-md-4">
    <h1>@{{ post_user.username }}</h1>
</div>
{% endblock %} {% block post_content %}
<div class="col-md-8">
    {% for post in post_list %} {% include "posts/_post.html" %} {% endfor %}
</div>
{% endblock post_content %}